import { StartupArgs } from "./StartupTypes";

export const defaultStartupArguments: StartupArgs = {
  admin: {password: ""},
  vars: {
    "3dSpotting": true,
    "3pCam": true,
    autoBalance: false,
    bulletDamage: 1,
    crossHair: true,
    friendlyFire: true,
    gameModeCounter: 1,
    gamePassword: "",
    hud: true,
    idleBanRounds: false,
    idleTimeout: 9000,
    killCam: true,
    maxPlayers: 100,
    miniMap: true,
    miniMapSpotting: true,
    nameTag: true,
    onlySquadLeaderSpawn: false,
    playerManDownTime: 1,
    playerRespawnTime: 1,
    premiumStatus: false,
    ranked: false,
    regenerateHealth: true,
    roundLockdownCountdown: 10,
    roundRestartPlayerCount: 0,
    roundStartPlayerCount: 8,
    serverDescription: "",
    serverMessage: "",
    serverName: "",
    soldierHealth: 1,
    teamKillCountForKick: 0,
    teamKillKickForBan: 0,
    teamKillValueDecreasePerSecond: 0.01,
    teamKillValueForKick: 2,
    teamKillValuelncrease: 0.525,
    unlockMode: undefined,
    vehicleSpawnAllowed: true,
    vehicleSpawnDelay: 1,
  },
  RM: {
    autoPerfEnabled: false,
    autoPerfMaxPlayers: 80,
    battleCryLink: "",
    defaultPreRoundTime: 45,
    ingameBanner: "",
    pingLimitEnable: true,
    pingLimitInMs: 250,
    serverInfo: "",
    serverLicenseKey: "",
    setAdmins: "",
    setAutoBalancer: false,
    setDevelopers: "",
    setLightAdmins: "",
    tempReservedSlotsEnabled: true,
    tempReservedSlotsRejoinTime: 180
  },
  vu: {
    serverBanner: ""
  },
  reservedSlots: {
    add: ""
  },
}

export const StartupDescriptions = {
  admin: {
    password: "Password used for connecting to server with PROCON"
  },
  vars: {
    ranked:  "Change the server between ranked/unranked mode",
    serverName:  "Set the server name",
    gamePassword:  "Set the game password for the server",
    autoBalance:  "Set if the server should autobalance",
    roundStartPlayerCount:  "Set minimum numbers of players to go from warm-up to pre-round/in-round",
    roundRestartPlayerCount:  "Set minimum numbers of players to go from in-round to warm-up",
    roundLockdownCountdown:  "Set the duration of pre-round",
    serverMessage:  "Set the server welcome message",
    friendlyFire:  "Set if the server should allow team damage",
    maxPlayers:  "Set desired maximum number of players",
    serverDescription:  "Set server description",
    killCam:  "Set if killcam is enabled",
    miniMap:  "Set if minimap is enabled",
    hud:  "Set if HUD is enabled",
    crossHair:  "Set if crosshair for all weapons is enabled",
    "3dSpotting":  "Set if spotted targets are visible in the 3d-world",
    miniMapSpotting:  "Set if spotted targets are visible on the minimap",
    nameTag:  "Set if nametags should be displayed",
    "3pCam":  "Set if allowing to toggle to third person vehicle cameras",
    regenerateHealth:  "Set if health regeneration should be active",
    teamKillCountForKick:  "Set number of teamkills allowed during a round",
    teamKillValueForKick:  "Set max kill-value allowed for a player before he/she is kicked",
    teamKillValuelncrease:  "Set kill-value increase for a teamkill",
    teamKillValueDecreasePerSecond:  "Set kill-value decrease per second",
    teamKillKickForBan:  "Set number of team-kill kicks that will lead to permaban",
    idleTimeout:  "Set idle timeout",
    idleBanRounds:  "Set how many rounds idle timeout should ban (if at all)",
    vehicleSpawnAllowed:  "Set whether vehicles should spawn in-game",
    vehicleSpawnDelay:  "Set vehicle spawn delay scale factor",
    soldierHealth:  "Set soldier max health scale factor",
    playerRespawnTime:  "Set player respawn time scale factor",
    playerManDownTime:  "Set player man-down time scale factor",
    bulletDamage:  "Set bullet damage scale factor",
    gameModeCounter:  "Set scale factor for number of tickets to end round",
    onlySquadLeaderSpawn:  "Set if players can only spawn on their squad leader",
    unlockMode:  "Set weapons & gadgets to be available on an unranked server",
    premiumStatus:  "Set if the server should be exclusive to Premium Players",
  },
  RM: {
    setDevelopers:  "Set list of developers, separated by a space",
    setAdmins:  "Set list of admins, separated by a space",
    setLightAdmins:  "Set list of light-admins, separated by a space",
    serverInfo:  "a description for your server",
    serverLicenseKey:  "RM Server License Key",
    ingameBanner:  "a link to an image",
    pingLimitEnable:  "activate ping limit",
    pingLimitInMs:  "time in ms",
    autoPerfEnabled:  "activate auto perf",
    autoPerfMaxPlayers:  "cutoff for auto perf",
    tempReservedSlotsEnabled:  "enable automatic rejoining",
    tempReservedSlotsRejoinTime:  "how long before rejoin is removed",
    defaultPreRoundTime:  "time before round starts",
    setAutoBalancer:  "autobalance",
    battleCryLink:  "link to your battlecry JSON endpoint",
  },
  vu: {
    serverBanner: "link to your server banner image"
  },
  reservedSlots: {
    add: "list of players to add to reserved slot separated by comma ,"
  }
}