import { StartupArgs } from "./StartupTypes";

export type formBuilderTypes = typeof formBuilderInputTypes

export const formBuilderInputTypes = {
  admin: {password: 'text'},
  vars: {
    _3dSpotting: 'checkbox',
    _3pCam: 'checkbox',
    autoBalance: 'checkbox',
    bulletDamage: 'number',
    crossHair: 'checkbox',
    friendlyFire: 'checkbox',
    gameModeCounter: 'number',
    gamePassword: 'text',
    hud: 'checkbox',
    idleBanRounds: 'checkbox',
    idleTimeout: 'number',
    killCam: 'checkbox',
    maxPlayers: 'number',
    miniMap: 'checkbox',
    miniMapSpotting: 'checkbox',
    nameTag: 'checkbox',
    onlySquadLeaderSpawn: 'checkbox',
    playerManDownTime: 'number',
    playerRespawnTime: 'number',
    ranked: 'checkbox',
    regenerateHealth: 'checkbox',
    roundLockdownCountdown: 'number',
    roundRestartPlayerCount: 'number',
    roundStartPlayerCount: 'number',
    serverDescription: 'textarea',
    serverMessage: 'textarea',
    serverName: 'text',
    soldierHealth: 'number',
    teamKillCountForKick: 'number',
    teamKillKickForBan: 'number',
    teamKillValueDecreasePerSecond: 'number',
    teamKillValueForKick: 'number',
    teamKillValuelncrease: 'number',
    // unlockMode: 'none',
    vehicleSpawnAllowed: 'checkbox',
    vehicleSpawnDelay: 'number',
  },
  RM: {
    autoPerfEnabled: 'checkbox',
    autoPerfMaxPlayers: 'number',
    battleCryLink: 'text',
    defaultPreRoundTime: 'number',
    ingameBanner: 'text',
    pingLimitEnable: 'checkbox',
    pingLimitInMs: 'number',
    serverInfo: 'text',
    serverLicenseKey: 'text',
    setAdmins: 'text',
    setAutoBalancer: 'checkbox',
    setDevelopers: 'text',
    setLightAdmins: 'text',
    tempReservedSlotsEnabled: 'checkbox',
    tempReservedSlotsRejoinTime: 'number',
  },
  vu: {
    ColorCorrectionEnabled: 'checkbox',
    DesertingAllowed: 'checkbox',
    DestructionEnabled: 'checkbox',
    HighPerformanceReplication: 'checkbox',
    ServerBanner: 'text',
    SetTeamTicketCount: 'setTeamTicketCount',
    SquadSize: 'number',
    SunFlareEnabled: 'checkbox',
    SuppressionMultiplier: 'number',
    FriendlyFireSuppression: 'checkbox',
    TimeScale: 'number',
    VehicleDisablingEnabled: 'checkbox',
    HttpAssetUrl: 'text',
    DisablePreRound: 'checkbox',
    TeamActivatedMines: 'checkbox',
    CorpseDamageEnabled: 'checkbox',
  },
  reservedSlots: 'reservedSlots' ,
}

export const defaultStartupArguments: StartupArgs = {
  admin: {password: ""},
  vars: {
    _3dSpotting: true,
    _3pCam: true,
    autoBalance: false,
    bulletDamage: 1,
    crossHair: true,
    friendlyFire: false,
    gameModeCounter: 1,
    gamePassword: "",
    hud: true,
    idleBanRounds: false,
    idleTimeout: 9000,
    killCam: true,
    maxPlayers: 100,
    miniMap: true,
    miniMapSpotting: true,
    nameTag: true,
    onlySquadLeaderSpawn: false,
    playerManDownTime: 1,
    playerRespawnTime: 1,
    ranked: false,
    regenerateHealth: true,
    roundLockdownCountdown: 10,
    roundRestartPlayerCount: 0,
    roundStartPlayerCount: 8,
    serverDescription: "",
    serverMessage: "",
    serverName: "",
    soldierHealth: 1,
    teamKillCountForKick: 0,
    teamKillKickForBan: 0,
    teamKillValueDecreasePerSecond: 0.01,
    teamKillValueForKick: 2.0,
    teamKillValuelncrease: 0.525,
    // unlockMode: undefined,
    vehicleSpawnAllowed: true,
    vehicleSpawnDelay: 1,
  },
  RM: {
    autoPerfEnabled: false,
    autoPerfMaxPlayers: 80,
    battleCryLink: "",
    defaultPreRoundTime: 45,
    ingameBanner: "",
    pingLimitEnable: true,
    pingLimitInMs: 250,
    serverInfo: "",
    serverLicenseKey: "",
    setAdmins: "",
    setAutoBalancer: false,
    setDevelopers: "",
    setLightAdmins: "",
    tempReservedSlotsEnabled: true,
    tempReservedSlotsRejoinTime: 180
  },
  vu: {
    ColorCorrectionEnabled: true,
    DesertingAllowed: false,
    DestructionEnabled: true,
    HighPerformanceReplication: false,
    ServerBanner: "",
    SetTeamTicketCount: [],
    SquadSize: 4,
    SunFlareEnabled: true,
    SuppressionMultiplier: 100,
    FriendlyFireSuppression: false,
    TimeScale: 1.0,
    VehicleDisablingEnabled: true,
    HttpAssetUrl: "",
    DisablePreRound: false,
    TeamActivatedMines: false,
    CorpseDamageEnabled: false,
  },
  reservedSlots: [""],
}