export const allMaps = [
  {
    mapCode: 'MP_001',
    displayName: 'Grand Bazaar',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_003',
    displayName: 'Teheran Highway',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_007',
    displayName: 'Caspian Border',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_011',
    displayName: 'Seine Crossing',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_012',
    displayName: 'Operation Firestorm',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_013',
    displayName: 'Damavand Peak',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_017',
    displayName: 'Noshahr Canals',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_018',
    displayName: 'Kharg Island',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_Subway',
    displayName: 'Operation Metro',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP1_001',
    displayName: 'Strike at Karkand',
    gameModes: [
      'ConquestAssaultLarge0',
      'ConquestAssaultSmall0',
      'ConquestAssaultSmall1',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP1_002',
    displayName: 'Gulf of Oman',
    gameModes: [
      'ConquestAssaultSmall0',
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP1_003',
    displayName: 'Sharqi Peninsula',
    gameModes: [
      'ConquestAssaultLarge0',
      'ConquestAssaultSmall0',
      'ConquestAssaultSmall1',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP1_004',
    displayName: 'Wake Island',
    gameModes: [
      'ConquestAssaultLarge0',
      'ConquestAssaultSmall0',
      'ConquestAssaultSmall1',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP2_Palace',
    displayName: 'Donya Fortress',
    gameModes: ['Domination0', 'GunMaster0', 'SquadDeathMatch0', 'TeamDeathMatchC0'],
  },
  {
    mapCode: 'XP2_Office',
    displayName: 'Operation 925',
    gameModes: ['Domination0', 'GunMaster0', 'SquadDeathMatch0', 'TeamDeathMatchC0'],
  },
  {
    mapCode: 'XP2_Factory',
    displayName: 'Scrapmetal',
    gameModes: ['Domination0', 'GunMaster0', 'SquadDeathMatch0', 'TeamDeathMatchC0'],
  },
  {
    mapCode: 'XP2_Skybar',
    displayName: 'Ziba Tower',
    gameModes: ['Domination0', 'GunMaster0', 'SquadDeathMatch0', 'TeamDeathMatchC0'],
  },
  {
    mapCode: 'XP3_Alborz',
    displayName: 'Alborz Mountains',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TankSuperiority0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP3_Shield',
    displayName: 'Armored Shield',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TankSuperiority0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP3_Desert',
    displayName: 'Bandar Desert',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TankSuperiority0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP3_Valley',
    displayName: 'Death Valley',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TankSuperiority0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP4_Parl',
    displayName: 'Azadi Palace',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'GunMaster0',
      'RushLarge0',
      'Scavenger0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP4_Quake',
    displayName: 'Epicenter',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'GunMaster0',
      'RushLarge0',
      'Scavenger0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP4_FD',
    displayName: 'Markaz Monolith',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'GunMaster0',
      'RushLarge0',
      'Scavenger0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP4_Rubble',
    displayName: 'Talah Market',
    gameModes: [
      'ConquestAssaultLarge0',
      'ConquestAssaultSmall0',
      'GunMaster0',
      'RushLarge0',
      'Scavenger0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP5_001',
    displayName: 'Operation Riverside',
    gameModes: [
      'AirSuperiority0',
      'CaptureTheFlag0',
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP5_002',
    displayName: 'Nebandan Flats',
    gameModes: [
      'AirSuperiority0',
      'CaptureTheFlag0',
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP5_003',
    displayName: 'Kiasar Railroad',
    gameModes: [
      'AirSuperiority0',
      'CaptureTheFlag0',
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP5_004',
    displayName: 'Sabalan Pipeline',
    gameModes: [
      'AirSuperiority0',
      'CaptureTheFlag0',
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
]

export const RealityModGameModes = [
  'AdvanceAndSecureStd',
  'AdvanceAndSecureAlt',
  'InsurgencyStd',
  'SkirmishStd',
  'TrainingStd',
]
