export const mapCodeToName = {
  ['MP_001']: 'Grand Bazaar',
  ['MP_003']: 'Teheran Highway',
  ['MP_007']: 'Caspian Border',
  ['MP_011']: 'Seine Crossing',
  ['MP_012']: 'Operation Firestorm',
  ['MP_013']: 'Damavand Peak',
  ['MP_017']: 'Noshahr Canals',
  ['MP_018']: 'Kharg Island',
  ['MP_Subway']: 'Operation Metro',
  ['XP1_001']: 'Strike at Karkand',
  ['XP1_002']: 'Gulf of Oman',
  ['XP1_003']: 'Sharqi Peninsula',
  ['XP1_004']: 'Wake Island',
  ['XP2_Palace']: 'Donya Fortress',
  ['XP2_Office']: 'Operation 925',
  ['XP2_Factory']: 'Scrapmetal',
  ['XP2_Skybar']: 'Ziba Tower',
  ['XP3_Alborz']: 'Alborz Mountains',
  ['XP3_Shield']: 'Armored Shield',
  ['XP3_Desert']: 'Bandar Desert',
  ['XP3_Valley']: 'Death Valley',
  ['XP4_Parl']: 'Azadi Palace',
  ['XP4_Quake']: 'Epicenter',
  ['XP4_FD']: 'Markaz Monolith',
  ['XP4_Rubble']: 'Talah Market',
  ['XP5_001']: 'Operation Riverside',
  ['XP5_002']: 'Nebandan Flats',
  ['XP5_003']: 'Kiasar Railroad',
  ['XP5_004']: 'Sabalan Pipeline',
}

export const allMaps = [
  {
    mapCode: 'MP_001',
    displayName: 'Grand Bazaar',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_003',
    displayName: 'Teheran Highway',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_007',
    displayName: 'Caspian Border',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_011',
    displayName: 'Seine Crossing',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_012',
    displayName: 'Operation Firestorm',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_013',
    displayName: 'Damavand Peak',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_017',
    displayName: 'Noshahr Canals',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_018',
    displayName: 'Kharg Island',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'MP_Subway',
    displayName: 'Operation Metro',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP1_001',
    displayName: 'Strike at Karkand',
    gameModes: [
      'ConquestAssaultLarge0',
      'ConquestAssaultSmall0',
      'ConquestAssaultSmall1',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP1_002',
    displayName: 'Gulf of Oman',
    gameModes: [
      'ConquestAssaultSmall0',
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP1_003',
    displayName: 'Sharqi Peninsula',
    gameModes: [
      'ConquestAssaultLarge0',
      'ConquestAssaultSmall0',
      'ConquestAssaultSmall1',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP1_004',
    displayName: 'Wake Island',
    gameModes: [
      'ConquestAssaultLarge0',
      'ConquestAssaultSmall0',
      'ConquestAssaultSmall1',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP2_Palace',
    displayName: 'Donya Fortress',
    gameModes: ['Domination0', 'GunMaster0', 'SquadDeathMatch0', 'TeamDeathMatchC0'],
  },
  {
    mapCode: 'XP2_Office',
    displayName: 'Operation 925',
    gameModes: ['Domination0', 'GunMaster0', 'SquadDeathMatch0', 'TeamDeathMatchC0'],
  },
  {
    mapCode: 'XP2_Factory',
    displayName: 'Scrapmetal',
    gameModes: ['Domination0', 'GunMaster0', 'SquadDeathMatch0', 'TeamDeathMatchC0'],
  },
  {
    mapCode: 'XP2_Skybar',
    displayName: 'Ziba Tower',
    gameModes: ['Domination0', 'GunMaster0', 'SquadDeathMatch0', 'TeamDeathMatchC0'],
  },
  {
    mapCode: 'XP3_Alborz',
    displayName: 'Alborz Mountains',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TankSuperiority0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP3_Shield',
    displayName: 'Armored Shield',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TankSuperiority0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP3_Desert',
    displayName: 'Bandar Desert',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TankSuperiority0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP3_Valley',
    displayName: 'Death Valley',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TankSuperiority0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP4_Parl',
    displayName: 'Azadi Palace',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'GunMaster0',
      'RushLarge0',
      'Scavenger0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP4_Quake',
    displayName: 'Epicenter',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'GunMaster0',
      'RushLarge0',
      'Scavenger0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP4_FD',
    displayName: 'Markaz Monolith',
    gameModes: [
      'ConquestLarge0',
      'ConquestSmall0',
      'GunMaster0',
      'RushLarge0',
      'Scavenger0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP4_Rubble',
    displayName: 'Talah Market',
    gameModes: [
      'ConquestAssaultLarge0',
      'ConquestAssaultSmall0',
      'GunMaster0',
      'RushLarge0',
      'Scavenger0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP5_001',
    displayName: 'Operation Riverside',
    gameModes: [
      'AirSuperiority0',
      'CaptureTheFlag0',
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP5_002',
    displayName: 'Nebandan Flats',
    gameModes: [
      'AirSuperiority0',
      'CaptureTheFlag0',
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP5_003',
    displayName: 'Kiasar Railroad',
    gameModes: [
      'AirSuperiority0',
      'CaptureTheFlag0',
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
  {
    mapCode: 'XP5_004',
    displayName: 'Sabalan Pipeline',
    gameModes: [
      'AirSuperiority0',
      'CaptureTheFlag0',
      'ConquestLarge0',
      'ConquestSmall0',
      'RushLarge0',
      'SquadDeathMatch0',
      'SquadRush0',
      'TeamDeathMatch0',
      'TeamDeathMatchC0',
    ],
  },
]

export const RealityModGameModes = [
  'AdvanceAndSecureStd',
  'AdvanceAndSecureAlt',
  'InsurgencyStd',
  'SkirmishStd',
  'TrainingStd',
]
