import { StartupArgs } from "./StartupTypes";

export const defaultStartupArguments: StartupArgs = {
  admin: {password: ""},
  vars: {
    "3dSpotting": true,
    "3pCam": true,
    autoBalance: true,
    bulletDamage: 1,
    crossHair: true,
    friendlyFire: true,
    gameModeCounter: 1,
    gamePassword: "",
    hud: true,
    idleBanRounds: false,
    idleTimeout: undefined,
    killCam: true,
    maxPlayers: 100,
    miniMap: true,
    miniMapSpotting: true,
    nameTag: true,
    onlySquadLeaderSpawn: false,
    playerManDownTime: undefined,
    playerRespawnTime: undefined,
    premiumStatus: false,
    ranked: false,
    regenerateHealth: true,
    roundLockdownCountdown: undefined,
    roundRestartPlayerCount: undefined,
    roundStartPlayerCount: undefined,
    serverDescription: undefined,
    serverMessage: undefined,
    serverName: "",
    soldierHealth: undefined,
    teamKillCountForKick: undefined,
    teamKillKickForBan: undefined,
    teamKillValueDecreasePerSecond: undefined,
    teamKillValueForKick: undefined,
    teamKillValuelncrease: undefined,
    unlockMode: undefined,
    vehicleSpawnAllowed: true,
    vehicleSpawnDelay: undefined,
  },
  RM: {
    autoPerfEnabled: false,
    autoPerfMaxPlayers: 80,
    battleCryLink: "",
    defaultPreRoundTime: 45,
    ingameBanner: "",
    pingLimitEnable: true,
    pingLimitInMs: 250,
    serverInfo: "",
    serverLicenseKey: "",
    setAdmins: [""],
    setAutoBalancer: false,
    setDevelopers: [""],
    setLightAdmins: [""],
    tempReservedSlotsEnabled: true,
    tempReservedSlotsRejoinTime: 180
  },
  vu: {
    serverBanner: ""
  },
  reservedSlots: [""],
}